version: '3.8'

services:
  # Servicio de Base de Datos (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: leetcode-db
    restart: always
    environment:
      POSTGRES_DB: algoritmiadb
      POSTGRES_USER: brandon
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio de Caché (Redis)
  cache:
    image: redis:7-alpine
    container_name: leetcode-cache
    restart: always
    ports:
      - "6379:6379"

  # Servicio de Mensajería (RabbitMQ)
  queue:
    image: rabbitmq:3-management-alpine
    container_name: leetcode-queue
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  # Servicio de Monitorización (Prometheus)
  prometheus:
    image: prom/prometheus:latest
    container_name: leetcode-metrics
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Servicio de la Aplicación (Spring Boot)
  app:
    build: .
    container_name: leetcode-app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
      - queue
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/algoritmiadb
      - SPRING_DATASOURCE_USERNAME=brandon
      - SPRING_DATASOURCE_PASSWORD=password123

volumes:
  postgres_data:
