# Configuración Base
spring.application.name=entorno-algoritmia-offline

# Perfil activo por defecto
spring.profiles.active=dev

# Gestión de dependencias de Spring Cloud (necesario para Resilience4j)
spring.cloud.compatibility-verifier.enabled=false

# Configuración de Jackson para JSON
spring.jackson.serialization.indent_output=true
app.mensaje=Hola desde el perfil por defecto
spring.mail.host=localhost
spring.rabbitmq.host=localhost
spring.batch.job.enabled=false
