# Perfil de Producción (Ecosistema Docker)
spring.datasource.url=jdbc:postgresql://db:5432/algoritmiadb
spring.datasource.username=admin
spring.datasource.password=password123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Redis Cache
spring.data.redis.host=cache
spring.data.redis.port=6379
spring.cache.type=redis

# RabbitMQ
spring.rabbitmq.host=queue

# Actuator metrics
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.tracing.sampling.probability=1.0
spring.zipkin.base-url=http://zipkin:9411
