-- Migración Inicial: Creación de tablas base
-- Flyway ejecutará esto automáticamente al detectar que la base de datos está vacía.

CREATE TABLE IF NOT EXISTS transaccion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado VARCHAR(255) NOT NULL,
    monto DOUBLE PRECISION NOT NULL,
    fecha TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS cartas_tarot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    arcano VARCHAR(20) NOT NULL,
    significado VARCHAR(500)
);
